languageCode = "en-us"
title = "Brokkr"
baseurl = "https://www.brokkr.io/"

[params]
  custom_css = ["css/foundation.min.css", "css/app.css"]
  custom_js = ["js/vendor/foundation.min.js", "js/app.js", "js/vendor/what-input.js"]
